# .github/workflows/fetch.yml
name: "Scheduled Feed Fetch"

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug: print package.json
        run: |
          echo ">>>> package.json <<<<"
          cat package.json

      - name: Debug: list workspace files
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug: print first lines of fetchFeeds.js
        run: |
          echo ">>>> fetchFeeds.js <<<<"
          sed -n '1,20p' fetchFeeds.js

      - name: Run fetch script directly
        run: node fetchFeeds.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add items.json
          if ! git diff --quiet --cached; then
            git commit -m "chore: update items.json with new feed items"
            git push
          else
            echo "No changes to commit."
          fi