# .github/workflows/fetch.yml
name: Scheduled Feed Fetch

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug: list workspace files
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        run: npm run fetch

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add items.json
          if ! git diff --quiet --cached; then
            git commit -m "chore: update items.json with new feed items"
            git push
          else
            echo "No changes to commit."
          fi