name: "Manual Fetch Test"

on:
  workflow_dispatch:

jobs:
  run-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print package.json
        run: cat package.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetch
        run: npm run fetch